{% set name = "python-jose-cryptodome" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9226693ee9ff52795ea8bfc70e0b77c62dca9a0f0fcbf9635c248d190211826e

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - ecdsa
    - future
    - pycryptodome
    - six

test:
  requires:
    - python {{ python_min }}
  imports:
    - jose
    - jose.backends

about:
  home: http://github.com/capless/python-jose-cryptodome
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "JOSE implementation in Python using pycryptodome"
  dev_url: http://github.com/capless/python-jose-cryptodome

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - benhuff
